version: '3.9'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  deno-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    container_name: deno-api
    env_file:
      - .env