version: "3.3"
services:
  deno-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: deno-api
    volumes:
      - ./images/:/images
    environment:
      DB_LINK: ${DB_LINK}
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}
      SERVER_PORT: ${SERVER_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      SIGN_ALG: ${SIGN_ALG}
      KEY_GEN_ALG: ${KEY_GEN_ALG}
      KEY_GEN_CURVE: ${KEY_GEN_CURVE}
      FULLCHAIN_PEM: ${FULLCHAIN_PEM}
      PRIVKEY_PEM: ${PRIVKEY_PEM}
    restart: always