version: '3.9'
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  deno-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: deno-api
    environment:
      DB_LINK: "mongodb://mongo-db:27017"
    env_file:
      - .env