version: "3.3"
services:
  mongo-db:
    image: mongo:4.4.14
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

  deno-api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    container_name: deno-api
    environment:
      DB_LINK: ${DB_LINK}
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}
      SERVER_PORT: ${SERVER_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      SIGN_ALG: ${SIGN_ALG}
      KEY_GEN_ALG: ${KEY_GEN_ALG}
      KEY_GEN_CURVE: ${KEY_GEN_CURVE}
      FULLCHAIN_PEM: ${FULLCHAIN_PEM}
      PRIVKEY_PEM: ${PRIVATE_KEY}
    restart: always