name: CD

on:
  push:
    branches: [ main, apk-downloadable ]

permissions:
  contents: write

jobs:
  docu-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ready-to-ride.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          cd backend
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env
          cat .env

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Android App
        run: |
          cd frontend
          ./gradlew assembleDebug
          cp ./app/build/outputs/apk/debug/app-debug.apk ./../backend/

      - name: Deploy
        env:
          DB_LINK: ${{ secrets.DB_LINK }}
          CERT_PATH: ${{ secrets.CERT_PATH }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          ENVIRONMENT: prod
          SIGN_ALG: ${{ secrets.SIGN_ALG }}
          KEY_GEN_ALG: ${{ secrets.KEY_GEN_ALG }}
          KEY_GEN_CURVE: ${{ secrets.KEY_GEN_CURVE }}
          FULLCHAIN_PEM: ${{ secrets.FULLCHAIN_PEM }}
          PRIVKEY_PEM: ${{ secrets.PRIVKEY_PEM }}
        uses: wshihadeh/docker-deployment-action@master
        with:
          remote_docker_host: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: false
          deploy_path: /deployment-test
          stack_file_name: backend/docker-compose.yaml
          pull_images_first: true
          keep_files: 5
          args: up -d --build