name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.22.0"

      - name: Run tests
        run: |
          cd ./backend/
          deno run --allow-net --allow-write --allow-read --allow-env main.ts

      - name: Run linter
        run: |
          cd ./backend/
          rm -rf packages
          deno lint