name: Deploy

on:
  push:
    branches:
      - setup-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: setup-docker

      - name: Create env file
        run: |
          ls
          touch .env
          echo ${{ secrets.ENV_FILE }} >> .env
          cat .env

      - name: Test
        run: ls

      - name: Start Deployment without copy
        uses: wshihadeh/docker-deployment-action@master
        with:
          remote_docker_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: false
          deploy_path: /deployment-test
          stack_file_name: backend/docker-compose.yaml
          pull_images_first: false
          keep_files: 3
          args: up -d --build